// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuartzServices.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Framework.Core {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class QuartzServices
  {
    static readonly string __ServiceName = "org.cooze.grpc.service.QuartzServices";

    static readonly grpc::Marshaller<global::Framework.Core.ScheduleModel> __Marshaller_ScheduleModel = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Framework.Core.ScheduleModel.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Framework.Core.QuartzNetResult> __Marshaller_QuartzNetResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Framework.Core.QuartzNetResult.Parser.ParseFrom);

    static readonly grpc::Method<global::Framework.Core.ScheduleModel, global::Framework.Core.QuartzNetResult> __Method_RunScheduleJob = new grpc::Method<global::Framework.Core.ScheduleModel, global::Framework.Core.QuartzNetResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RunScheduleJob",
        __Marshaller_ScheduleModel,
        __Marshaller_QuartzNetResult);

    static readonly grpc::Method<global::Framework.Core.ScheduleModel, global::Framework.Core.QuartzNetResult> __Method_StopScheduleJob = new grpc::Method<global::Framework.Core.ScheduleModel, global::Framework.Core.QuartzNetResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopScheduleJob",
        __Marshaller_ScheduleModel,
        __Marshaller_QuartzNetResult);

    static readonly grpc::Method<global::Framework.Core.ScheduleModel, global::Framework.Core.QuartzNetResult> __Method_RemoveJob = new grpc::Method<global::Framework.Core.ScheduleModel, global::Framework.Core.QuartzNetResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveJob",
        __Marshaller_ScheduleModel,
        __Marshaller_QuartzNetResult);

    static readonly grpc::Method<global::Framework.Core.ScheduleModel, global::Framework.Core.QuartzNetResult> __Method_StopScheduleAsync = new grpc::Method<global::Framework.Core.ScheduleModel, global::Framework.Core.QuartzNetResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopScheduleAsync",
        __Marshaller_ScheduleModel,
        __Marshaller_QuartzNetResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Framework.Core.QuartzServicesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of QuartzServices</summary>
    public abstract partial class QuartzServicesBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Framework.Core.QuartzNetResult> RunScheduleJob(global::Framework.Core.ScheduleModel request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Framework.Core.QuartzNetResult> StopScheduleJob(global::Framework.Core.ScheduleModel request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Framework.Core.QuartzNetResult> RemoveJob(global::Framework.Core.ScheduleModel request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Framework.Core.QuartzNetResult> StopScheduleAsync(global::Framework.Core.ScheduleModel request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for QuartzServices</summary>
    public partial class QuartzServicesClient : grpc::ClientBase<QuartzServicesClient>
    {
      /// <summary>Creates a new client for QuartzServices</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public QuartzServicesClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for QuartzServices that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public QuartzServicesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected QuartzServicesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected QuartzServicesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Framework.Core.QuartzNetResult RunScheduleJob(global::Framework.Core.ScheduleModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RunScheduleJob(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Framework.Core.QuartzNetResult RunScheduleJob(global::Framework.Core.ScheduleModel request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RunScheduleJob, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Framework.Core.QuartzNetResult> RunScheduleJobAsync(global::Framework.Core.ScheduleModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RunScheduleJobAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Framework.Core.QuartzNetResult> RunScheduleJobAsync(global::Framework.Core.ScheduleModel request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RunScheduleJob, null, options, request);
      }
      public virtual global::Framework.Core.QuartzNetResult StopScheduleJob(global::Framework.Core.ScheduleModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopScheduleJob(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Framework.Core.QuartzNetResult StopScheduleJob(global::Framework.Core.ScheduleModel request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StopScheduleJob, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Framework.Core.QuartzNetResult> StopScheduleJobAsync(global::Framework.Core.ScheduleModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopScheduleJobAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Framework.Core.QuartzNetResult> StopScheduleJobAsync(global::Framework.Core.ScheduleModel request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StopScheduleJob, null, options, request);
      }
      public virtual global::Framework.Core.QuartzNetResult RemoveJob(global::Framework.Core.ScheduleModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveJob(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Framework.Core.QuartzNetResult RemoveJob(global::Framework.Core.ScheduleModel request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveJob, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Framework.Core.QuartzNetResult> RemoveJobAsync(global::Framework.Core.ScheduleModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveJobAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Framework.Core.QuartzNetResult> RemoveJobAsync(global::Framework.Core.ScheduleModel request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveJob, null, options, request);
      }
      public virtual global::Framework.Core.QuartzNetResult StopScheduleAsync(global::Framework.Core.ScheduleModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopScheduleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Framework.Core.QuartzNetResult StopScheduleAsync(global::Framework.Core.ScheduleModel request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StopScheduleAsync, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Framework.Core.QuartzNetResult> StopScheduleAsyncAsync(global::Framework.Core.ScheduleModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopScheduleAsyncAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Framework.Core.QuartzNetResult> StopScheduleAsyncAsync(global::Framework.Core.ScheduleModel request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StopScheduleAsync, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override QuartzServicesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new QuartzServicesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(QuartzServicesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RunScheduleJob, serviceImpl.RunScheduleJob)
          .AddMethod(__Method_StopScheduleJob, serviceImpl.StopScheduleJob)
          .AddMethod(__Method_RemoveJob, serviceImpl.RemoveJob)
          .AddMethod(__Method_StopScheduleAsync, serviceImpl.StopScheduleAsync).Build();
    }

  }
}
#endregion
